# train
BATCH_SIZE: 64
LR: 0.001
NUM_WORKERS: 8
EPOCHS: 200
VERBOSE: True
TRAIN_PRINT: 200
VAL_PRINT: 20

# model
MODEL: 'resnet18_15class'
RTN_ID: True
WEIGHTS: '2024-06-17-17-20-46-1718641246_incremental_expansion_mstr'
FREEZE:
PRED_CLASS_MAP_ID: 3


# data
DATASET: 'stg'
DATA_ROOT:
AVC_CLASSES: ['contrast-A2C', 'contrast-A3C', 'contrast-A4C', 'contrast-PLAX']
RESOLUTION: 112
TRAIN_TRANSFORMS: True
INP_DIM: 1
NORM: 'z'
