# train
BATCH_SIZE: 64
LR: 0.001
NUM_WORKERS: 8
EPOCHS: 200
VERBOSE: True
TRAIN_PRINT: 200
VAL_PRINT: 20

# model
MODEL: 'resnet18_15class'
RTN_ID: True
WEIGHTS: '2024-06-17-12-50-53-1718625053_incremental_expansion_wase'
FREEZE:
PRED_CLASS_MAP_ID: 1


# data
DATASET: 'camus'
DATA_ROOT:
AVC_CLASSES: ['noncontrast-A2C', 'noncontrast-A4C']
RESOLUTION: 112
TRAIN_TRANSFORMS: True
INP_DIM: 1
NORM: 'z'
